# Generated by Django 2.1 on 2018-08-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.CharField(default='10', max_length=2),
        ),
    ]
