# Generated by Django 2.1 on 2018-08-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.CharField(default='https://api.adorable.io/avatars/285/abott@adorable', max_length=256),
        ),
    ]
