# Generated by Django 2.1 on 2018-08-16 03:17

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('number', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='Postko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('number', models.IntegerField()),
                ('slug', models.SlugField(unique=True)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
