# Generated by Django 2.1 on 2018-08-16 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_postcommenten_postcommentko'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tag_en', to='posting.Posten')),
            ],
        ),
        migrations.CreateModel(
            name='PostTagko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tag_en', to='posting.Postko')),
            ],
        ),
    ]
